replicaCount: 1

image:
  repository: nginx-web-app  # Will be overridden by helm command
  tag: "latest"             # Will be overridden by helm command
  pullPolicy: IfNotPresent  # Will be overridden to Never for local deployment

security:
  podSecurityContext:
    runAsNonRoot: false
  containerSecurityContext:
    allowPrivilegeEscalation: false

resources:
  limits:
    cpu: "500m"
    memory: "512Mi"
  requests:
    cpu: "200m"
    memory: "256Mi"

probes:
  livenessProbe:
    initialDelaySeconds: 10
    periodSeconds: 10
  readinessProbe:
    initialDelaySeconds: 5
    periodSeconds: 5

service:
  type: ClusterIP  # Changed to ClusterIP since we'll use Ingress
  port: 80

ingress:
  enabled: false
  className: "nginx"
  annotations: {}
    # kubernetes.io/ingress.class: nginx
    # kubernetes.io/tls-acme: "true"
  hosts:
    - host: chart-example.local
      paths:
        - path: /
          pathType: Prefix
  tls: []
  #  - secretName: chart-example-tls
  #    hosts:
  #      - chart-example.local

configMap:
  message: "This is prod"
