apiVersion: kustomize.toolkit.fluxcd.io/v1
kind: Kustomization
metadata:
  name: demo
spec:
  interval: 5m
  path: ./manifest/demo.yaml
  force: true
  prune: true
  sourceRef:
    kind: GitRepository
    name: flux-system