apiVersion: apps/v1
kind: Deployment
metadata:
  name: {{ include "web-app.fullname" . }}
  labels:
    {{- include "web-app.labels" . | nindent 4 }}
spec:
  replicas: {{ .Values.replicaCount }}
  selector:
    matchLabels:
      {{- include "web-app.selectorLabels" . | nindent 6 }}
  template:
    metadata:
      labels:
        {{- include "web-app.selectorLabels" . | nindent 8 }}
    spec:
      # Pod-level security context
      {{- if .Values.podSecurityContext.enabled }}
      securityContext:
        runAsNonRoot: true
        fsGroup: {{ .Values.podSecurityContext.fsGroup }}
      {{- end }}

      {{- with .Values.image.pullSecrets }}
      imagePullSecrets:
        {{- toYaml . | nindent 8 }}
      {{- end }}
      containers:
        - name: {{ .Chart.Name }}
          image: "{{ .Values.image.repository }}:{{ .Values.image.tag }}"
          imagePullPolicy: {{ .Values.image.pullPolicy }}
          # Container security context
          {{- if .Values.containerSecurityContext.enabled }}
          securityContext:
            runAsUser: 101  # Nginx user in alpine
            runAsGroup: 101            
            allowPrivilegeEscalation: false
            capabilities:
              drop:
                - ALL
          {{- end }}
          # Resource limits
          resources:
            limits:
              cpu: "{{ .Values.resources.limits.cpu }}"
              memory: "{{ .Values.resources.limits.memory }}"
            requests:
              cpu: "{{ .Values.resources.requests.cpu }}"
              memory: "{{ .Values.resources.requests.memory }}"
          # Health checks
          livenessProbe:
            httpGet:
              path: /
              port: 8080
            initialDelaySeconds: {{ .Values.probes.livenessProbe.initialDelaySeconds }}
            periodSeconds: {{ .Values.probes.livenessProbe.periodSeconds }}
          readinessProbe:
            httpGet:
              path: /
              port: 8080
            initialDelaySeconds: {{ .Values.probes.readinessProbe.initialDelaySeconds }}
            periodSeconds: {{ .Values.probes.readinessProbe.periodSeconds }}
          ports:
            - containerPort: 8080
              protocol: TCP
          volumeMounts:
            - name: nginx-config
              mountPath: /etc/nginx/nginx.conf
              subPath: nginx.conf
            - name: nginx-config
              mountPath: /usr/share/nginx/html/index.html
              subPath: index.html
            - name: tmp-volume
              mountPath: /tmp
            - name: tmp-run
              mountPath: /var/run
      volumes:
        - name: nginx-config
          configMap:
            name: {{ include "web-app.fullname" . }}-config
        - name: tmp-volume
          emptyDir: {}
        - name: tmp-run
          emptyDir: {}
