name: Build and Deploy Web App

on:
  push:
    branches: [ main ]
    tags: v1.2.3 # Trigger on semantic version tags (v1.2.3 format)
  pull_request:
    branches: [ main ]

env:
  REGISTRY: docker.io
  IMAGE_NAME: ${{ github.repository_owner }}/nginx-web-app

jobs:
  version:
    runs-on: ubuntu-latest
    outputs:
      version: ${{ steps.get_version.outputs.version }}
    steps:
      - name: Checkout
        uses: actions/checkout@v3
        with:
          fetch-depth: 0

      - name: Get Version
        id: get_version
        run: |
          # If this is a semantic version tag (v1.2.3)
          if [[ $GITHUB_REF =~ refs/tags/v([0-9]+\.[0-9]+\.[0-9]+) ]]; then
            echo "version=${BASH_REMATCH[1]}" >> $GITHUB_OUTPUT
          # For branches/other tags use commit-based version
          else
            echo "version=0.0.0-$(date +'%Y%m%d')-${GITHUB_SHA::8}" >> $GITHUB_OUTPUT
          fi

  build-and-test:
    needs: version
    runs-on: ubuntu-latest
    permissions:
      contents: read
      packages: write
    
    steps:
    - name: Checkout repository
      uses: actions/checkout@v3

    - name: Set up QEMU for multi-arch
      uses: docker/setup-qemu-action@v2

    - name: Set up Docker Buildx
      uses: docker/setup-buildx-action@v2
      with:
        driver-opts: |
          network=host

    - name: Log in to Docker Hub
      uses: docker/login-action@v2
      with:
        registry: ${{ env.REGISTRY }}
        username: ${{ secrets.DOCKERHUB_USERNAME }}
        password: ${{ secrets.DOCKERHUB_TOKEN }}

    - name: Build and push multi-arch image
      uses: docker/build-push-action@v4
      with:
        context: demo/image
        file: demo/image/Dockerfile
        platforms: linux/amd64,linux/arm64
        push: ${{ github.event_name != 'pull_request' }}
        tags: |
          ${{ env.REGISTRY }}/${{ env.IMAGE_NAME }}:${{ needs.version.outputs.version }}
          ${{ env.REGISTRY }}/${{ env.IMAGE_NAME }}:latest
        cache-from: type=gha
        cache-to: type=gha,mode=max

    - name: Scan with Trivy (AMD64)
      if: success() && github.event_name != 'pull_request'
      uses: aquasecurity/trivy-action@master
      with:
        image-ref: ${{ env.REGISTRY }}/${{ env.IMAGE_NAME }}:${{ needs.version.outputs.version }}
        format: 'sarif'
        exit-code: ${{ github.event_name == 'push' && '1' || '0' }}
        ignore-unfixed: true
        vuln-type: 'os,library'
        severity: 'CRITICAL,HIGH'
        platform: linux/amd64
        trivyignores: 'demo/image/.trivyignore'

  validate-helm:
    runs-on: ubuntu-latest
    needs: build-and-test
    
    steps:
    - name: Checkout repository
      uses: actions/checkout@v3

    - name: Set up Helm
      uses: azure/setup-helm@v3
      with:
        version: v3.11.2

    - name: Lint Helm Chart
      run: |
        cd demo/package/charts/web-app
        helm lint .

  deploy-local:
    runs-on: ubuntu-latest
    needs: [validate-helm, version]
    if: github.event_name != 'pull_request'
    environment: production
    permissions:
      contents: read
      packages: write
    
    steps:
    - name: Checkout repository
      uses: actions/checkout@v3

    - name: Set up kubectl
      uses: azure/setup-kubectl@v3

    - name: Create kind cluster
      uses: helm/kind-action@v1.5.0
      with:
        cluster_name: kind
        node_image: kindest/node:v1.27.3@sha256:3966ac761ae0136263ffdb6cfd4db23ef8a83cba8a463690e98317add2c9ba72  # AMD64
        wait: 30s

    - name: Set up Helm
      uses: azure/setup-helm@v3
      with:
        version: v3.11.2

    - name: Deploy to local cluster
      run: |
        # Pull AMD64 image specifically
        FULL_IMAGE_NAME="${{ env.REGISTRY }}/${{ env.IMAGE_NAME }}"
        VERSION="${{ needs.version.outputs.version }}"
        
        docker pull --platform linux/amd64 "${FULL_IMAGE_NAME}:${VERSION}"
        kind load docker-image "${FULL_IMAGE_NAME}:${VERSION}" --name kind
        
        # Deploy with helm using semantic version
        helm upgrade --install web-app demo/package/charts/web-app \
          --set image.repository=${{ env.REGISTRY }}/${{ env.IMAGE_NAME }} \
          --set image.tag=${{ needs.version.outputs.version }} \
          --set image.pullPolicy=IfNotPresent \
          --debug --wait --timeout 2m
        
        # Verify deployment
        kubectl get pods -o wide -w