name: Build and Deploy Web App

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

env:
  REGISTRY: docker.io
  IMAGE_NAME: ${{ github.repository_owner }}/nginx-web-app  # Your Docker Hub username/image-name

jobs:
  version:
    runs-on: ubuntu-latest
    outputs:
      version: ${{ steps.get_version.outputs.version }}
    steps:
      - name: Checkout
        uses: actions/checkout@v3
        with:
          fetch-depth: 0

      - name: Get Version
        id: get_version
        run: |
          # If this is a tag, use the tag name
          if [[ $GITHUB_REF == refs/tags/* ]]; then
            echo "version=${GITHUB_REF#refs/tags/}" >> $GITHUB_OUTPUT
          else
            # Otherwise use commit sha with date
            echo "version=$(date +'%Y%m%d')-${GITHUB_SHA::8}" >> $GITHUB_OUTPUT
          fi

  build-and-test:
    needs: version
    runs-on: ubuntu-latest
    permissions:
      contents: read
      packages: write
    
    steps:
    - name: Checkout repository
      uses: actions/checkout@v3



    - name: Set up Docker Buildx
      uses: docker/setup-buildx-action@v2

    - name: Log in to Docker Hub
      uses: docker/login-action@v2
      with:
        registry: ${{ env.REGISTRY }}
        username: ${{ secrets.DOCKERHUB_USERNAME }}
        password: ${{ secrets.DOCKERHUB_TOKEN }}

    - name: Build Docker image
      uses: docker/build-push-action@v4
      with:
        context: demo/image
        file: demo/image/Dockerfile
        push: false # Don't push yet, we'll push after scanning
        tags: |
          ${{ env.REGISTRY }}/${{ env.IMAGE_NAME }}:${{ needs.version.outputs.version }}
          ${{ env.REGISTRY }}/${{ env.IMAGE_NAME }}:latest
          ${{ env.REGISTRY }}/${{ env.IMAGE_NAME }}:${{ github.sha }}
        cache-from: type=gha
        cache-to: type=gha,mode=max
        outputs: type=docker,dest=/tmp/image.tar # Save image for scanning

    - name: Run Trivy vulnerability scanner
      uses: aquasecurity/trivy-action@master
      with:
        input: /tmp/image.tar
        format: 'table'
        exit-code: '1'
        ignore-unfixed: true
        vuln-type: 'os,library'
        severity: 'CRITICAL,HIGH'
        trivyignores: 'demo/image/.trivyignore'

    - name: Push Docker image
      if: success() # Only push if vulnerability scan passes
      uses: docker/build-push-action@v4
      with:
        context: demo/image
        file: demo/image/Dockerfile
        push: ${{ github.event_name != 'pull_request' }}
        tags: |
          ${{ env.REGISTRY }}/${{ env.IMAGE_NAME }}:${{ needs.version.outputs.version }}
          ${{ env.REGISTRY }}/${{ env.IMAGE_NAME }}:latest
          ${{ env.REGISTRY }}/${{ env.IMAGE_NAME }}:${{ github.sha }}
        cache-from: type=gha
        cache-to: type=gha,mode=max

  validate-helm:
    runs-on: ubuntu-latest
    needs: build-and-test
    
    steps:
    - name: Checkout repository
      uses: actions/checkout@v3

    - name: Set up Helm
      uses: azure/setup-helm@v3
      with:
        version: v3.11.2

    - name: Set up Python
      uses: actions/setup-python@v4
      with:
        python-version: '3.10'

    - name: Install kubeval
      run: |
        wget https://github.com/instrumenta/kubeval/releases/latest/download/kubeval-linux-amd64.tar.gz
        tar xf kubeval-linux-amd64.tar.gz
        sudo cp kubeval /usr/local/bin

    - name: Lint Helm Chart
      run: |
        cd demo/package/charts/web-app
        helm lint .

    - name: Validate Kubernetes manifests
      run: |
        cd demo/package/charts/web-app
        helm template . | kubeval --strict

  deploy-local:
    runs-on: ubuntu-latest
    needs: [validate-helm, version]
    if: github.event_name != 'pull_request'
    environment: production
    permissions:
      contents: read
      packages: write
    
    steps:
    - name: Checkout repository
      uses: actions/checkout@v3

    - name: Set up kubectl
      uses: azure/setup-kubectl@v3

    - name: Create kind cluster
      uses: helm/kind-action@v1.5.0
      with:
        cluster_name: kind
        wait: 30s

    - name: Set up Helm
      uses: azure/setup-helm@v3
      with:
        version: v3.11.2

    - name: Deploy to local cluster
      run: |
        # Log in to Docker Hub again to ensure we can pull
        echo "${{ secrets.DOCKERHUB_TOKEN }}" | docker login -u ${{ secrets.DOCKERHUB_USERNAME }} --password-stdin
        
        # Pull and load the image into kind
        FULL_IMAGE_NAME="${{ env.REGISTRY }}/${{ env.IMAGE_NAME }}"
        LOCAL_IMAGE_NAME="${{ env.IMAGE_NAME }}"
        VERSION="${{ needs.version.outputs.version }}"
        
        echo "Pulling image: ${FULL_IMAGE_NAME}:${VERSION}"
        docker pull "${FULL_IMAGE_NAME}:${VERSION}"
        
        echo "Retagging image for kind"
        docker tag "${FULL_IMAGE_NAME}:${VERSION}" "${LOCAL_IMAGE_NAME}:${VERSION}"
        
        echo "Loading image into kind cluster"
        kind load docker-image "${LOCAL_IMAGE_NAME}:${VERSION}" --name kind
        
        # Deploy with helm using the local image name
        helm upgrade --install web-app demo/package/charts/web-app \
          --set image.repository=${{ env.IMAGE_NAME }} \
          --set image.tag=${{ needs.version.outputs.version }} \
          --set image.pullPolicy=Never \
          --debug --wait --timeout 3m
        
        # Check pod status
        echo "Checking pod status..."
        kubectl get pods -l app.kubernetes.io/name=web-app -o wide
        echo "Pod details:"
        kubectl describe pods -l app.kubernetes.io/name=web-app
